### ISSUE TITLE
why no reuters results?

### ISSUE THREAD

**Issue by hanggun** [EGiunchiglia/C-HMCNN#2]

**Comment by EGiunchiglia** [comment]
We could find a dataset called Reuters, however it had different number of features and labels from the one reported in the paper [`Hierarchical Multi-Label Classification Networks`](http://proceedings.mlr.press/v80/wehrmann18a/wehrmann18a.pdf). In order to avoid an unfair comparison (as we do not have their code), we did not include that dataset.
